// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/chord.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Node's identifier
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // Node's socket ip:port
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type NodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Base *BaseReq `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *NodeReq) Reset() {
	*x = NodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReq) ProtoMessage() {}

func (x *NodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReq.ProtoReflect.Descriptor instead.
func (*NodeReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{1}
}

func (x *NodeReq) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeReq) GetBase() *BaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

type NodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node     *Node     `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	BaseResp *BaseResp `protobuf:"bytes,2,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
}

func (x *NodeResp) Reset() {
	*x = NodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResp) ProtoMessage() {}

func (x *NodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResp.ProtoReflect.Descriptor instead.
func (*NodeResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{2}
}

func (x *NodeResp) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *NodeResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

// Empty Request struct for some method
// that do not need to send extra information
// except the node itself
type BaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts int64 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"` // 时间戳
}

func (x *BaseReq) Reset() {
	*x = BaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseReq) ProtoMessage() {}

func (x *BaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseReq.ProtoReflect.Descriptor instead.
func (*BaseReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{3}
}

func (x *BaseReq) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type BaseResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrNo   int32  `protobuf:"varint,1,opt,name=err_no,json=errNo,proto3" json:"err_no,omitempty"`
	ErrTips string `protobuf:"bytes,2,opt,name=err_tips,json=errTips,proto3" json:"err_tips,omitempty"`
	Ts      int64  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *BaseResp) Reset() {
	*x = BaseResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResp) ProtoMessage() {}

func (x *BaseResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResp.ProtoReflect.Descriptor instead.
func (*BaseResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{4}
}

func (x *BaseResp) GetErrNo() int32 {
	if x != nil {
		return x.ErrNo
	}
	return 0
}

func (x *BaseResp) GetErrTips() string {
	if x != nil {
		return x.ErrTips
	}
	return ""
}

func (x *BaseResp) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type IDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base *BaseReq `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *IDReq) Reset() {
	*x = IDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDReq) ProtoMessage() {}

func (x *IDReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDReq.ProtoReflect.Descriptor instead.
func (*IDReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{5}
}

func (x *IDReq) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *IDReq) GetBase() *BaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetValReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Base *BaseReq `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *GetValReq) Reset() {
	*x = GetValReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValReq) ProtoMessage() {}

func (x *GetValReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValReq.ProtoReflect.Descriptor instead.
func (*GetValReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{6}
}

func (x *GetValReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetValReq) GetBase() *BaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetValResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    []byte    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	BaseResp *BaseResp `protobuf:"bytes,2,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
}

func (x *GetValResp) Reset() {
	*x = GetValResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValResp) ProtoMessage() {}

func (x *GetValResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValResp.ProtoReflect.Descriptor instead.
func (*GetValResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{7}
}

func (x *GetValResp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetValResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Pair) Reset() {
	*x = Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{8}
}

func (x *Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pair *Pair    `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Base *BaseReq `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *SetKeyReq) Reset() {
	*x = SetKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyReq) ProtoMessage() {}

func (x *SetKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyReq.ProtoReflect.Descriptor instead.
func (*SetKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{9}
}

func (x *SetKeyReq) GetPair() *Pair {
	if x != nil {
		return x.Pair
	}
	return nil
}

func (x *SetKeyReq) GetBase() *BaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

type SetKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       []byte    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BaseResp *BaseResp `protobuf:"bytes,2,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
}

func (x *SetKeyResp) Reset() {
	*x = SetKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKeyResp) ProtoMessage() {}

func (x *SetKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKeyResp.ProtoReflect.Descriptor instead.
func (*SetKeyResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{10}
}

func (x *SetKeyResp) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SetKeyResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type DeleteKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Base *BaseReq `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *DeleteKeyReq) Reset() {
	*x = DeleteKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyReq) ProtoMessage() {}

func (x *DeleteKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyReq.ProtoReflect.Descriptor instead.
func (*DeleteKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteKeyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteKeyReq) GetBase() *BaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

type DeleteKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Id       []byte    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BaseResp *BaseResp `protobuf:"bytes,3,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
}

func (x *DeleteKeyResp) Reset() {
	*x = DeleteKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResp) ProtoMessage() {}

func (x *DeleteKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResp.ProtoReflect.Descriptor instead.
func (*DeleteKeyResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteKeyResp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteKeyResp) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DeleteKeyResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type MultiDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Base *BaseReq `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *MultiDeleteReq) Reset() {
	*x = MultiDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiDeleteReq) ProtoMessage() {}

func (x *MultiDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiDeleteReq.ProtoReflect.Descriptor instead.
func (*MultiDeleteReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{13}
}

func (x *MultiDeleteReq) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MultiDeleteReq) GetBase() *BaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

type MultiDeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys         []string  `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	AffectedKeys int32     `protobuf:"varint,2,opt,name=affected_keys,json=affectedKeys,proto3" json:"affected_keys,omitempty"`
	BaseResp     *BaseResp `protobuf:"bytes,3,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
}

func (x *MultiDeleteResp) Reset() {
	*x = MultiDeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiDeleteResp) ProtoMessage() {}

func (x *MultiDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiDeleteResp.ProtoReflect.Descriptor instead.
func (*MultiDeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{14}
}

func (x *MultiDeleteResp) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *MultiDeleteResp) GetAffectedKeys() int32 {
	if x != nil {
		return x.AffectedKeys
	}
	return 0
}

func (x *MultiDeleteResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

type GetKeysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   []byte   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Base *BaseReq `protobuf:"bytes,3,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *GetKeysReq) Reset() {
	*x = GetKeysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeysReq) ProtoMessage() {}

func (x *GetKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeysReq.ProtoReflect.Descriptor instead.
func (*GetKeysReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{15}
}

func (x *GetKeysReq) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetKeysReq) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetKeysReq) GetBase() *BaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

type GetKeysResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs    []*Pair   `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	BaseResp *BaseResp `protobuf:"bytes,2,opt,name=baseResp,proto3" json:"baseResp,omitempty"`
}

func (x *GetKeysResp) Reset() {
	*x = GetKeysResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetKeysResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeysResp) ProtoMessage() {}

func (x *GetKeysResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeysResp.ProtoReflect.Descriptor instead.
func (*GetKeysResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{16}
}

func (x *GetKeysResp) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *GetKeysResp) GetBaseResp() *BaseResp {
	if x != nil {
		return x.BaseResp
	}
	return nil
}

var File_proto_chord_proto protoreflect.FileDescriptor

var file_proto_chord_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22,
	0x42, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62,
	0x61, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x19, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x62, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x19, 0x0a, 0x07, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x22, 0x4c, 0x0a, 0x08,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x5f,
	0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x72, 0x72, 0x4e, 0x6f, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x74, 0x69, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x54, 0x69, 0x70, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x73, 0x22, 0x35, 0x0a, 0x05, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x22, 0x3b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x49,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x2e, 0x0a, 0x04, 0x50, 0x61, 0x69,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x44, 0x0a, 0x09, 0x53, 0x65, 0x74,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x04, 0x70, 0x61, 0x69, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x04, 0x70, 0x61, 0x69,
	0x72, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x22,
	0x43, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a,
	0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x3e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04,
	0x62, 0x61, 0x73, 0x65, 0x22, 0x58, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x42,
	0x0a, 0x0e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x22, 0x71, 0x0a, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x25,
	0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08, 0x62, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52,
	0x04, 0x62, 0x61, 0x73, 0x65, 0x22, 0x51, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72,
	0x73, 0x12, 0x25, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0xd2, 0x03, 0x0a, 0x05, 0x43, 0x68, 0x6f,
	0x72, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x12, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x09,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x08, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d,
	0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x08, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a,
	0x0d, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x06,
	0x2e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x24, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x6b, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x12, 0x06, 0x2e, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x08, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23,
	0x0a, 0x0c, 0x53, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x08,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x0a, 0x2e,
	0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x47, 0x65, 0x74, 0x56,
	0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79,
	0x12, 0x0a, 0x2e, 0x53, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x53,
	0x65, 0x74, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x0b, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x0b, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x0c, 0x2e, 0x47, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x25, 0x5a,
	0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x73,
	0x74, 0x6f, 0x6e, 0x65, 0x79, 0x2f, 0x78, 0x6c, 0x5f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_chord_proto_rawDescOnce sync.Once
	file_proto_chord_proto_rawDescData = file_proto_chord_proto_rawDesc
)

func file_proto_chord_proto_rawDescGZIP() []byte {
	file_proto_chord_proto_rawDescOnce.Do(func() {
		file_proto_chord_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_chord_proto_rawDescData)
	})
	return file_proto_chord_proto_rawDescData
}

var file_proto_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_chord_proto_goTypes = []interface{}{
	(*Node)(nil),            // 0: Node
	(*NodeReq)(nil),         // 1: NodeReq
	(*NodeResp)(nil),        // 2: NodeResp
	(*BaseReq)(nil),         // 3: BaseReq
	(*BaseResp)(nil),        // 4: BaseResp
	(*IDReq)(nil),           // 5: IDReq
	(*GetValReq)(nil),       // 6: GetValReq
	(*GetValResp)(nil),      // 7: GetValResp
	(*Pair)(nil),            // 8: Pair
	(*SetKeyReq)(nil),       // 9: SetKeyReq
	(*SetKeyResp)(nil),      // 10: SetKeyResp
	(*DeleteKeyReq)(nil),    // 11: DeleteKeyReq
	(*DeleteKeyResp)(nil),   // 12: DeleteKeyResp
	(*MultiDeleteReq)(nil),  // 13: MultiDeleteReq
	(*MultiDeleteResp)(nil), // 14: MultiDeleteResp
	(*GetKeysReq)(nil),      // 15: GetKeysReq
	(*GetKeysResp)(nil),     // 16: GetKeysResp
}
var file_proto_chord_proto_depIdxs = []int32{
	0,  // 0: NodeReq.node:type_name -> Node
	3,  // 1: NodeReq.base:type_name -> BaseReq
	0,  // 2: NodeResp.node:type_name -> Node
	4,  // 3: NodeResp.baseResp:type_name -> BaseResp
	3,  // 4: IDReq.base:type_name -> BaseReq
	3,  // 5: GetValReq.base:type_name -> BaseReq
	4,  // 6: GetValResp.baseResp:type_name -> BaseResp
	8,  // 7: SetKeyReq.pair:type_name -> Pair
	3,  // 8: SetKeyReq.base:type_name -> BaseReq
	4,  // 9: SetKeyResp.baseResp:type_name -> BaseResp
	3,  // 10: DeleteKeyReq.base:type_name -> BaseReq
	4,  // 11: DeleteKeyResp.baseResp:type_name -> BaseResp
	3,  // 12: MultiDeleteReq.base:type_name -> BaseReq
	4,  // 13: MultiDeleteResp.baseResp:type_name -> BaseResp
	3,  // 14: GetKeysReq.base:type_name -> BaseReq
	8,  // 15: GetKeysResp.pairs:type_name -> Pair
	4,  // 16: GetKeysResp.baseResp:type_name -> BaseResp
	3,  // 17: Chord.GetPredecessor:input_type -> BaseReq
	3,  // 18: Chord.GetSuccessor:input_type -> BaseReq
	1,  // 19: Chord.Notify:input_type -> NodeReq
	5,  // 20: Chord.FindSuccessor:input_type -> IDReq
	5,  // 21: Chord.ChekPredecessor:input_type -> IDReq
	1,  // 22: Chord.SetPredecessor:input_type -> NodeReq
	1,  // 23: Chord.SetSuccessor:input_type -> NodeReq
	6,  // 24: Chord.GetVal:input_type -> GetValReq
	9,  // 25: Chord.SetKey:input_type -> SetKeyReq
	11, // 26: Chord.DeleteKey:input_type -> DeleteKeyReq
	13, // 27: Chord.MultiDelete:input_type -> MultiDeleteReq
	15, // 28: Chord.GetKeys:input_type -> GetKeysReq
	2,  // 29: Chord.GetPredecessor:output_type -> NodeResp
	2,  // 30: Chord.GetSuccessor:output_type -> NodeResp
	4,  // 31: Chord.Notify:output_type -> BaseResp
	2,  // 32: Chord.FindSuccessor:output_type -> NodeResp
	4,  // 33: Chord.ChekPredecessor:output_type -> BaseResp
	4,  // 34: Chord.SetPredecessor:output_type -> BaseResp
	4,  // 35: Chord.SetSuccessor:output_type -> BaseResp
	7,  // 36: Chord.GetVal:output_type -> GetValResp
	10, // 37: Chord.SetKey:output_type -> SetKeyResp
	12, // 38: Chord.DeleteKey:output_type -> DeleteKeyResp
	14, // 39: Chord.MultiDelete:output_type -> MultiDeleteResp
	16, // 40: Chord.GetKeys:output_type -> GetKeysResp
	29, // [29:41] is the sub-list for method output_type
	17, // [17:29] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_chord_proto_init() }
func file_proto_chord_proto_init() {
	if File_proto_chord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_chord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiDeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetKeysResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_chord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chord_proto_goTypes,
		DependencyIndexes: file_proto_chord_proto_depIdxs,
		MessageInfos:      file_proto_chord_proto_msgTypes,
	}.Build()
	File_proto_chord_proto = out.File
	file_proto_chord_proto_rawDesc = nil
	file_proto_chord_proto_goTypes = nil
	file_proto_chord_proto_depIdxs = nil
}
