// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/chord.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type CheckAliveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckAliveReq) Reset() {
	*x = CheckAliveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAliveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAliveReq) ProtoMessage() {}

func (x *CheckAliveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAliveReq.ProtoReflect.Descriptor instead.
func (*CheckAliveReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{1}
}

type CheckAliveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *CheckAliveResp) Reset() {
	*x = CheckAliveResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAliveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAliveResp) ProtoMessage() {}

func (x *CheckAliveResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAliveResp.ProtoReflect.Descriptor instead.
func (*CheckAliveResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAliveResp) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

type FindSuccessorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindSuccessorReq) Reset() {
	*x = FindSuccessorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSuccessorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorReq) ProtoMessage() {}

func (x *FindSuccessorReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorReq.ProtoReflect.Descriptor instead.
func (*FindSuccessorReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{3}
}

func (x *FindSuccessorReq) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type FindSuccessorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successor *Node `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
}

func (x *FindSuccessorResp) Reset() {
	*x = FindSuccessorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSuccessorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorResp) ProtoMessage() {}

func (x *FindSuccessorResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorResp.ProtoReflect.Descriptor instead.
func (*FindSuccessorResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{4}
}

func (x *FindSuccessorResp) GetSuccessor() *Node {
	if x != nil {
		return x.Successor
	}
	return nil
}

type GetPredecessorReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPredecessorReq) Reset() {
	*x = GetPredecessorReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredecessorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorReq) ProtoMessage() {}

func (x *GetPredecessorReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorReq.ProtoReflect.Descriptor instead.
func (*GetPredecessorReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{5}
}

type GetPredecessorResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Predecessor *Node `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
}

func (x *GetPredecessorResp) Reset() {
	*x = GetPredecessorResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPredecessorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPredecessorResp) ProtoMessage() {}

func (x *GetPredecessorResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPredecessorResp.ProtoReflect.Descriptor instead.
func (*GetPredecessorResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{6}
}

func (x *GetPredecessorResp) GetPredecessor() *Node {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

type NotifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node *Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyReq) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type NotifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyResp) Reset() {
	*x = NotifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResp) ProtoMessage() {}

func (x *NotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResp.ProtoReflect.Descriptor instead.
func (*NotifyResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{8}
}

type FindSuccessorFingerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	FingerId []byte `protobuf:"bytes,2,opt,name=finger_id,json=fingerId,proto3" json:"finger_id,omitempty"`
}

func (x *FindSuccessorFingerReq) Reset() {
	*x = FindSuccessorFingerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSuccessorFingerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorFingerReq) ProtoMessage() {}

func (x *FindSuccessorFingerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorFingerReq.ProtoReflect.Descriptor instead.
func (*FindSuccessorFingerReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{9}
}

func (x *FindSuccessorFingerReq) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FindSuccessorFingerReq) GetFingerId() []byte {
	if x != nil {
		return x.FingerId
	}
	return nil
}

type FindSuccessorFingerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index    int32  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	FingerId []byte `protobuf:"bytes,2,opt,name=finger_id,json=fingerId,proto3" json:"finger_id,omitempty"`
	Found    bool   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	NextNode *Node  `protobuf:"bytes,4,opt,name=next_node,json=nextNode,proto3" json:"next_node,omitempty"` // if found, next_node is the target node, otherwise it's the next_node to query finger table
}

func (x *FindSuccessorFingerResp) Reset() {
	*x = FindSuccessorFingerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindSuccessorFingerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindSuccessorFingerResp) ProtoMessage() {}

func (x *FindSuccessorFingerResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindSuccessorFingerResp.ProtoReflect.Descriptor instead.
func (*FindSuccessorFingerResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{10}
}

func (x *FindSuccessorFingerResp) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FindSuccessorFingerResp) GetFingerId() []byte {
	if x != nil {
		return x.FingerId
	}
	return nil
}

func (x *FindSuccessorFingerResp) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindSuccessorFingerResp) GetNextNode() *Node {
	if x != nil {
		return x.NextNode
	}
	return nil
}

type GetSuccessorListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSuccessorListReq) Reset() {
	*x = GetSuccessorListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSuccessorListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListReq) ProtoMessage() {}

func (x *GetSuccessorListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListReq.ProtoReflect.Descriptor instead.
func (*GetSuccessorListReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{11}
}

type GetSuccessorListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessorList []*Node `protobuf:"bytes,1,rep,name=successor_list,json=successorList,proto3" json:"successor_list,omitempty"`
}

func (x *GetSuccessorListResp) Reset() {
	*x = GetSuccessorListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSuccessorListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSuccessorListResp) ProtoMessage() {}

func (x *GetSuccessorListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSuccessorListResp.ProtoReflect.Descriptor instead.
func (*GetSuccessorListResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{12}
}

func (x *GetSuccessorListResp) GetSuccessorList() []*Node {
	if x != nil {
		return x.SuccessorList
	}
	return nil
}

type Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Pair) Reset() {
	*x = Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{13}
}

func (x *Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId []byte `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Entry *Pair  `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{14}
}

func (x *Data) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *Data) GetEntry() *Pair {
	if x != nil {
		return x.Entry
	}
	return nil
}

type StoreKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId []byte `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Entry *Pair  `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
}

func (x *StoreKeyReq) Reset() {
	*x = StoreKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyReq) ProtoMessage() {}

func (x *StoreKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyReq.ProtoReflect.Descriptor instead.
func (*StoreKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{15}
}

func (x *StoreKeyReq) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *StoreKeyReq) GetEntry() *Pair {
	if x != nil {
		return x.Entry
	}
	return nil
}

type StoreKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Located  bool  `protobuf:"varint,1,opt,name=located,proto3" json:"located,omitempty"` // true if the key is located the right place, false if key needs to be pass to next
	NextNode *Node `protobuf:"bytes,2,opt,name=next_node,json=nextNode,proto3" json:"next_node,omitempty"`
}

func (x *StoreKeyResp) Reset() {
	*x = StoreKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreKeyResp) ProtoMessage() {}

func (x *StoreKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreKeyResp.ProtoReflect.Descriptor instead.
func (*StoreKeyResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{16}
}

func (x *StoreKeyResp) GetLocated() bool {
	if x != nil {
		return x.Located
	}
	return false
}

func (x *StoreKeyResp) GetNextNode() *Node {
	if x != nil {
		return x.NextNode
	}
	return nil
}

type FindKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId []byte `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
}

func (x *FindKeyReq) Reset() {
	*x = FindKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindKeyReq) ProtoMessage() {}

func (x *FindKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindKeyReq.ProtoReflect.Descriptor instead.
func (*FindKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{17}
}

func (x *FindKeyReq) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

type FindKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Located  bool   `protobuf:"varint,1,opt,name=located,proto3" json:"located,omitempty"`
	KeyId    []byte `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Entry    *Pair  `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry,omitempty"`
	NextNode *Node  `protobuf:"bytes,4,opt,name=next_node,json=nextNode,proto3" json:"next_node,omitempty"`
}

func (x *FindKeyResp) Reset() {
	*x = FindKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindKeyResp) ProtoMessage() {}

func (x *FindKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindKeyResp.ProtoReflect.Descriptor instead.
func (*FindKeyResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{18}
}

func (x *FindKeyResp) GetLocated() bool {
	if x != nil {
		return x.Located
	}
	return false
}

func (x *FindKeyResp) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *FindKeyResp) GetEntry() *Pair {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *FindKeyResp) GetNextNode() *Node {
	if x != nil {
		return x.NextNode
	}
	return nil
}

type DeleteKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId []byte `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
}

func (x *DeleteKeyReq) Reset() {
	*x = DeleteKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyReq) ProtoMessage() {}

func (x *DeleteKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyReq.ProtoReflect.Descriptor instead.
func (*DeleteKeyReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteKeyReq) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

type DeleteKeyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Located  bool   `protobuf:"varint,1,opt,name=located,proto3" json:"located,omitempty"`
	KeyExist bool   `protobuf:"varint,2,opt,name=key_exist,json=keyExist,proto3" json:"key_exist,omitempty"`
	KeyId    []byte `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	NextNode *Node  `protobuf:"bytes,4,opt,name=next_node,json=nextNode,proto3" json:"next_node,omitempty"`
}

func (x *DeleteKeyResp) Reset() {
	*x = DeleteKeyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKeyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResp) ProtoMessage() {}

func (x *DeleteKeyResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResp.ProtoReflect.Descriptor instead.
func (*DeleteKeyResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteKeyResp) GetLocated() bool {
	if x != nil {
		return x.Located
	}
	return false
}

func (x *DeleteKeyResp) GetKeyExist() bool {
	if x != nil {
		return x.KeyExist
	}
	return false
}

func (x *DeleteKeyResp) GetKeyId() []byte {
	if x != nil {
		return x.KeyId
	}
	return nil
}

func (x *DeleteKeyResp) GetNextNode() *Node {
	if x != nil {
		return x.NextNode
	}
	return nil
}

type TakeOverKeysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *TakeOverKeysReq) Reset() {
	*x = TakeOverKeysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeOverKeysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverKeysReq) ProtoMessage() {}

func (x *TakeOverKeysReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverKeysReq.ProtoReflect.Descriptor instead.
func (*TakeOverKeysReq) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{21}
}

func (x *TakeOverKeysReq) GetData() []*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type TakeOverKeysResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TakeOverKeysResp) Reset() {
	*x = TakeOverKeysResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chord_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeOverKeysResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeOverKeysResp) ProtoMessage() {}

func (x *TakeOverKeysResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chord_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeOverKeysResp.ProtoReflect.Descriptor instead.
func (*TakeOverKeysResp) Descriptor() ([]byte, []int) {
	return file_proto_chord_proto_rawDescGZIP(), []int{22}
}

var File_proto_chord_proto protoreflect.FileDescriptor

var file_proto_chord_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22,
	0x0f, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x22, 0x24, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x22, 0x0a, 0x10, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x11, 0x46, 0x69,
	0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x23, 0x0a, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x22, 0x3d, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x27, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0b, 0x70, 0x72, 0x65,
	0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65,
	0x22, 0x0c, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4b,
	0x0a, 0x16, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x46,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x17,
	0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x46, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f,
	0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x12, 0x22, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x44, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x0e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x2e, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x3a, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x41, 0x0a,
	0x0b, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b, 0x65,
	0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x22, 0x4c, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x09, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x23,
	0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b, 0x65,
	0x79, 0x49, 0x64, 0x22, 0x7f, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b, 0x65,
	0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x22, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x22, 0x25, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x09, 0x6e,
	0x65, 0x78, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x22,
	0x2c, 0x0a, 0x0f, 0x54, 0x61, 0x6b, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x12, 0x0a,
	0x10, 0x54, 0x61, 0x6b, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x32, 0x87, 0x04, 0x0a, 0x05, 0x43, 0x68, 0x6f, 0x72, 0x64, 0x12, 0x2d, 0x0a, 0x0a, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x0e, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0d, 0x46, 0x69,
	0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x11, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x39, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x64, 0x65, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a,
	0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0a, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x48, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f,
	0x72, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x18, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72,
	0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x08, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x12,
	0x0b, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x46,
	0x69, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x0d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0c, 0x54, 0x61, 0x6b, 0x65, 0x4f, 0x76,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x10, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x4f, 0x76, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x4f,
	0x76, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x25, 0x5a, 0x23, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x72, 0x69, 0x73, 0x74, 0x6f,
	0x6e, 0x65, 0x79, 0x2f, 0x78, 0x6c, 0x5f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_chord_proto_rawDescOnce sync.Once
	file_proto_chord_proto_rawDescData = file_proto_chord_proto_rawDesc
)

func file_proto_chord_proto_rawDescGZIP() []byte {
	file_proto_chord_proto_rawDescOnce.Do(func() {
		file_proto_chord_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_chord_proto_rawDescData)
	})
	return file_proto_chord_proto_rawDescData
}

var file_proto_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_chord_proto_goTypes = []interface{}{
	(*Node)(nil),                    // 0: Node
	(*CheckAliveReq)(nil),           // 1: CheckAliveReq
	(*CheckAliveResp)(nil),          // 2: CheckAliveResp
	(*FindSuccessorReq)(nil),        // 3: FindSuccessorReq
	(*FindSuccessorResp)(nil),       // 4: FindSuccessorResp
	(*GetPredecessorReq)(nil),       // 5: GetPredecessorReq
	(*GetPredecessorResp)(nil),      // 6: GetPredecessorResp
	(*NotifyReq)(nil),               // 7: NotifyReq
	(*NotifyResp)(nil),              // 8: NotifyResp
	(*FindSuccessorFingerReq)(nil),  // 9: FindSuccessorFingerReq
	(*FindSuccessorFingerResp)(nil), // 10: FindSuccessorFingerResp
	(*GetSuccessorListReq)(nil),     // 11: GetSuccessorListReq
	(*GetSuccessorListResp)(nil),    // 12: GetSuccessorListResp
	(*Pair)(nil),                    // 13: Pair
	(*Data)(nil),                    // 14: Data
	(*StoreKeyReq)(nil),             // 15: StoreKeyReq
	(*StoreKeyResp)(nil),            // 16: StoreKeyResp
	(*FindKeyReq)(nil),              // 17: FindKeyReq
	(*FindKeyResp)(nil),             // 18: FindKeyResp
	(*DeleteKeyReq)(nil),            // 19: DeleteKeyReq
	(*DeleteKeyResp)(nil),           // 20: DeleteKeyResp
	(*TakeOverKeysReq)(nil),         // 21: TakeOverKeysReq
	(*TakeOverKeysResp)(nil),        // 22: TakeOverKeysResp
}
var file_proto_chord_proto_depIdxs = []int32{
	0,  // 0: FindSuccessorResp.successor:type_name -> Node
	0,  // 1: GetPredecessorResp.predecessor:type_name -> Node
	0,  // 2: NotifyReq.node:type_name -> Node
	0,  // 3: FindSuccessorFingerResp.next_node:type_name -> Node
	0,  // 4: GetSuccessorListResp.successor_list:type_name -> Node
	13, // 5: Data.entry:type_name -> Pair
	13, // 6: StoreKeyReq.entry:type_name -> Pair
	0,  // 7: StoreKeyResp.next_node:type_name -> Node
	13, // 8: FindKeyResp.entry:type_name -> Pair
	0,  // 9: FindKeyResp.next_node:type_name -> Node
	0,  // 10: DeleteKeyResp.next_node:type_name -> Node
	14, // 11: TakeOverKeysReq.data:type_name -> Data
	1,  // 12: Chord.CheckAlive:input_type -> CheckAliveReq
	3,  // 13: Chord.FindSuccessor:input_type -> FindSuccessorReq
	5,  // 14: Chord.GetPredecessor:input_type -> GetPredecessorReq
	7,  // 15: Chord.Notify:input_type -> NotifyReq
	9,  // 16: Chord.FindSuccessorFinger:input_type -> FindSuccessorFingerReq
	11, // 17: Chord.GetSuccessorList:input_type -> GetSuccessorListReq
	15, // 18: Chord.StoreKey:input_type -> StoreKeyReq
	17, // 19: Chord.FindKey:input_type -> FindKeyReq
	19, // 20: Chord.DeleteKey:input_type -> DeleteKeyReq
	21, // 21: Chord.TakeOverKeys:input_type -> TakeOverKeysReq
	2,  // 22: Chord.CheckAlive:output_type -> CheckAliveResp
	4,  // 23: Chord.FindSuccessor:output_type -> FindSuccessorResp
	6,  // 24: Chord.GetPredecessor:output_type -> GetPredecessorResp
	8,  // 25: Chord.Notify:output_type -> NotifyResp
	10, // 26: Chord.FindSuccessorFinger:output_type -> FindSuccessorFingerResp
	12, // 27: Chord.GetSuccessorList:output_type -> GetSuccessorListResp
	16, // 28: Chord.StoreKey:output_type -> StoreKeyResp
	18, // 29: Chord.FindKey:output_type -> FindKeyResp
	20, // 30: Chord.DeleteKey:output_type -> DeleteKeyResp
	22, // 31: Chord.TakeOverKeys:output_type -> TakeOverKeysResp
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_chord_proto_init() }
func file_proto_chord_proto_init() {
	if File_proto_chord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_chord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAliveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckAliveResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSuccessorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSuccessorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredecessorReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPredecessorResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSuccessorFingerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindSuccessorFingerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSuccessorListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSuccessorListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKeyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeOverKeysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chord_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeOverKeysResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_chord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chord_proto_goTypes,
		DependencyIndexes: file_proto_chord_proto_depIdxs,
		MessageInfos:      file_proto_chord_proto_msgTypes,
	}.Build()
	File_proto_chord_proto = out.File
	file_proto_chord_proto_rawDesc = nil
	file_proto_chord_proto_goTypes = nil
	file_proto_chord_proto_depIdxs = nil
}
